priority:
    resource: "@LynxPriorityBundle/Resources/config/routing.yml"
    type:     annotation
    prefix:   /priority

status:
    resource: "@LynxStatusBundle/Resources/config/routing.yml"
    type:     annotation
    prefix:   /status

sprint:
    resource: "@LynxSprintBundle/Resources/config/routing.yml"
    type:     annotation
    prefix:   /sprint

lynx_task:
    resource: "@LynxTaskBundle/Controller/"
    type:     annotation
    prefix:   /task

lynx_project:
    resource: "@LynxProjectBundle/Controller/"
    type:     annotation
    prefix:   /project

lynx_taskboard:
    resource: "@LynxTaskboardBundle/Controller/"
    type:     annotation
    prefix:   /taskboard

lynx_userpanel:
    resource: "@LynxUserpanelBundle/Controller/"
    type:     annotation
    prefix:   /userpanel

app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /user

app_manager:
    resource: "@AppManagerBundle/Controller/"
    type:     annotation
    prefix:   /manager

app_boot:
    resource: "@AppBootBundle/Controller/"
    type:     annotation
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile