# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        App\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
            
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            http_basic: ~
#            form_login:
#                provider: fos_userbundle
#                check_path: /oauth/v2/auth/login_check
#                login_path: /oauth/v2/auth/login
#            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN