# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        App\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12
            
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets|html)/
            security: false
        prod:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets|html)/
            security: false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/priority/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/status/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/sprint/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/task/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/project/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/taskboard/, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/userpanel/, roles: [ IS_AUTHENTICATED_FULLY ] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN